load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "thunder_client",
    srcs = glob([
        "thunder/*.py",
        "thunder_sandbox/*.py",
    ]),
    data = [
        "thunder/py.typed",
        "thunder_sandbox/py.typed",
    ],
    imports = ["."],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "package_metadata",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        "pyproject.toml",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "thunder_test",
    srcs = ["thunder_test.py"],
    deps = [":thunder_client"],
)
