load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_library(
    name = "thunder_client",
    srcs = glob([
        "src/thunder/*.py",
        "src/thunder_sandbox/*.py",
    ]),
    data = [
        "src/thunder/py.typed",
        "src/thunder_sandbox/py.typed",
    ],
    imports = ["src"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "package_metadata",
    srcs = [
        "LICENSE",
        "NOTICE",
        "README.md",
        "pyproject.toml",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "thunder_test",
    srcs = ["test/test_thunder.py"],
    main = "test/test_thunder.py",
    deps = [":thunder_client"],
)
